### ISSUE TITLE
Request to reflect Flexible Spellcasting slots accurately

### ISSUE THREAD

**Issue by Joshmvii7** [reonZ/pf2e-spells-summary#1]
Right now it still shows Flexible Spellcasting Archetype spell slots as though they're Vancian instead of pseudo spontaneous.

![image](https://user-images.githubusercontent.com/99048395/197276494-606fab69-4bb3-48da-9a2a-54c278d81443.png)

**Comment by reonZ** [comment]
`Flexible` prepared spells have been added in v1.1.0
