### ISSUE TITLE
Ritual spell entries make spell summary not work

### ISSUE THREAD

**Issue by xdy** [reonZ/pf2e-spells-summary#10]
Not sure what license the code in this repo is under so not sending a PR with a fix.

But then, it would be just adding optional chaining in two places on the same line. :)

On https://github.com/reonZ/pf2e-spells-summary/blob/6e289b04fb9273d3ad58808c5df09bd9d5783daf/src/sheet.ts#L104 change to
```
const isCharge = entry.system?.prepared?.value === 'charge'
```

**Comment by reonZ** [comment]
Thanks
