### ISSUE TITLE
PF2E Staves Compatibility is Broken

### ISSUE THREAD

**Issue by Unoblueboy** [reonZ/pf2e-spells-summary#15]
Hi,

I've used this module for a while and it looks like at some point the compatibility with PF2E Staves was broken. From the image attached, the spells Shield, Produce Flame, and Breathe Fire are from a staff but no spell type is shown for these. Also when you hover over these spells the number of remaining charges doesn't appear.

![image](https://github.com/reonZ/pf2e-spells-summary/assets/12022978/f6fadf5b-d378-4568-b790-5d696fdf9b6e)

I've tried to figure out what could be causing these issues, it looks like the variables `isCharge`, `isStaff`, and `charges` in the `getEntries` method may be the culpritsm, the following updates could fix it. 

https://github.com/reonZ/pf2e-spells-summary/blob/16ab8a8f1a7bd95db675804f67d6f80e40a081bb/src/sheet.ts
```diff
    data.spellcastingEntries.forEach(entry => {
+       const fullEntry = data.document.spellcasting.get(entry.id);
        if (entry.isRitual || !entry.hasCollection || !entry.levels.some(x => x.active.some(y => y !== null))) return

        const check = entry.statistic.check
        ...
        const entryId = entry.id
-       const isCharge = entry.system?.prepared?.value === 'charge'
-       const isStaff = getProperty(entry, 'flags.pf2e-staves.staveID') !== undefined
-       const charges = { value: getProperty<number>(entry, 'flags.pf2e-staves.charges') ?? 0, max: 0 }
+       const isCharge = fullEntry.system?.prepared?.value === 'charge'
+       const isStaff = getProperty(fullEntry, 'flags.pf2e-staves.staveID') !== undefined
+       const charges = { value: getProperty<number>(fullEntry, 'flags.pf2e-staves.charges') ?? 0, max: 0 }
```

I've briefly tested this and it doesn't seem to cause any issues (including for rituals).

**Comment by reonZ** [comment]
The module has been completely redone and is once again fully compatible with `PF2e Staves`
