### ISSUE TITLE
Show spellcasting entry of spells

### ISSUE THREAD

**Issue by xdy** [reonZ/pf2e-spells-summary#2]
It'd be useful if the summary showed what Spellcasting Entry it came from somewhere, perhaps if one hovers over Check/DC for the spell?
One player in my campaign only just now realized she has several Chill Touch cantrips. She has *way* too many spell entries... :)

**Comment by reonZ** [comment]
Yeah, i was about to do that at some point but never  settled on where to put it.

I will probably simply put a tooltip there then, thanks.

**Comment by reonZ** [comment]
The name of  the spellcasting entry is now displayed in a tooltip when hovering over the `Check/DC` value in version 1.1.1.
