### ISSUE TITLE
Layout is a bit tight for higher-level characters

### ISSUE THREAD

**Issue by xdy** [reonZ/pf2e-spells-summary#3]
With only the system and pf2e-spells-summary loaded it looks like this for some characters:
![image](https://user-images.githubusercontent.com/246024/197340216-e4a9522d-a067-4643-93c5-265945079463.png)
Maybe move Components a bit to the left to make room?

**Comment by reonZ** [comment]
I will take a loot at this, thanks.

**Comment by reonZ** [comment]
The value of `Check/DC` no longer wrap in version 1.1.1.
