### ISSUE TITLE
Compatibility wit PF2e Staves

### ISSUE THREAD

**Issue by MrChessur** [reonZ/pf2e-spells-summary#4]
A new module was recently released that added stave spellcasting using charges (https://github.com/jessev14/pf2e-staves). Was wondering if it would be possible to add compatibility with it as the spells from the staves will not cast while the spells are in the collapsed form. I will be posting a similar issue on their GitHub so hopefully this can become a possibility.

![image](https://user-images.githubusercontent.com/28309284/209892252-9fd26bc5-fe33-40d2-9f04-2ee6c85ef5aa.png)

**Comment by reonZ** [comment]
Sorry for not answering to you earlier, i kept pushing this and i should have given you some words at the very least.

The module is now compatible with `PF2e Staves` with version `1.2.0`

**Comment by MrChessur** [comment]
Thats awesome. Happy to see some cool spell modules in sync. Thanks for the speedy change. My groups will be happy.

**Comment by shemetz** [comment]
The compatibility here is so great, thank you!
