### ISSUE TITLE
Feature request:  add setting/toggle to hide grayed-out spells

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-spells-summary#5]
It would be nice to hide spells that can't be used today anymore.  This can be a client setting, or toggleable from within the sheet with some new toggle at the top.

![image](https://user-images.githubusercontent.com/6516621/219634734-d29924e0-c663-45b8-9991-bc5366ac1a7c.png) → ![image](https://user-images.githubusercontent.com/6516621/219634958-2f2a7278-4486-46b1-9f44-13f657fb9630.png)

**Comment by reonZ** [comment]
This could be done indeed.

**Comment by reonZ** [comment]
After some thinking, i don't think this is a good idea, hiding expanded spells will prevent you from interacting with that spell completely, you can't read its description, you can't send it to chat, you can't revert a mistake you could have eventually done.

**Comment by shemetz** [comment]
The way my group uses this module is that we rely on this "side" of the spells tab during the session, and click the tab to revert to the old version each time we need to make adjustments or change spell preparation or reset staff charges.  Also if we need to edit a spell, or read its details again.

Is this module's tab intended to support all of those features, or is it meant to be used in conjunction with the old/core spells tab?  Because if it's the second option, personally I would prefer to keep it "light" and focused on common usage, while expecting a flip to the "verbose side" on occasion.

**Comment by reonZ** [comment]
The alternate tab is meant to be used during playtime and mostly encounters, it offers everything you need to play your spellcaster except spellcasting entry manipulation.
