### ISSUE TITLE
Feature request:  Add setting to sort spells by spellcasting type (within levels)

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-spells-summary#6]
This should be a setting, because sorting alphabetically is probably still useful for many people, and I don't think the preference would change between different sheets.

Example of before and after:

![image](https://user-images.githubusercontent.com/6516621/219637714-46293e4c-9fe4-4e00-ab69-9aff5104d682.png) → 
![image](https://user-images.githubusercontent.com/6516621/219638007-743b1e46-24e9-495d-a123-9c11b97cba40.png)

**Comment by reonZ** [comment]
Yeah, i will see about it.

**Comment by reonZ** [comment]
I added the option to sort spells by types before alphabetically in the settings with version `1.3.0`
