### ISSUE TITLE
Feature request: show spontaneous spellcasting slot counts in headers for each spell level.

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-spells-summary#7]
This feature is needed for spontanous spellcasters because they don't know how many slots they have of each level while using this sheet, unless they hover over that area in the sheet.  Requiring the user to hover over something to know this information is not ideal (though the hover feature is still nice by itself).

The normal sheet already shows them, so adding this shouldn't be too hard (especially if you just skip the interactivity part).  It should only be shown for people who have spontaneous spellcasting, i.e. have X charges per level rather than having each spell individually prepared or not.  Flexible spellcasting should have the same thing.

Since these don't have to be interactive, it's also okay to just show text saying e.g. "2/3" rather than a special `[2] / [3]` visual.

Current "summary" sheet:
![image](https://user-images.githubusercontent.com/6516621/219645686-9adb7788-1bc1-49ac-8bfb-15c351a864a5.png)

Mock example of how it should look like (using the existing slot counters from the "core" sheet):
![image](https://user-images.githubusercontent.com/6516621/219646297-ba41f750-6ffd-40a9-b7e1-17b74c10b223.png)

Can be simplified to this:

![image](https://user-images.githubusercontent.com/6516621/219646915-361238f1-11e5-47e1-a0bb-9879a0b6a72a.png)

**Comment by reonZ** [comment]
Having stats in the header that only pertain to part of the data in that table is way too confusing.

Also it couldn't even work if the character has more than one spontaneous spellcasting entry. This is not doable.

**Comment by shemetz** [comment]
Yeah, this won't be a good solution for the problem.  Maybe there's a better way to display that information without requiring hover, which doesn't have these potential holes...
