### ISSUE TITLE
Feature request:  add setting to change which columns are shown

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-spells-summary#8]
The current choice of columns to show is pretty good, but my group had some issues with it:
- Spell DC and spell attack bonus are very redundant for someone who has the same values for everything. They're also pretty redundant for someone who does have different values and just doesn't care because they already know which of their spells are "weaker"
- Components are sometimes useful, but often aren't
- The "Range" which is shown on the normal spells tab is not shown here, which makes it difficult to choose a spell to cast during your turn, if you don't remember which of your spells have which range (a common problem).  Showing the ranges will let players easily tell at a glance which of their spells are useful right now.
- Similarly, it would be great to have an "Area" or "Targets" column (something not shown by the core pf2e system, but it exists in dnd5e and is nice!).
- It would be nice to have the "CAST" button at the rightmost, since it's the most used action button.  In fact, it could even change to only appear when hovering over the entry, because it doesn't provide any information by itself.

I think the solution should be to add some setting that toggles which columns are shown, maybe also at which order.  It would include adding some new columns (like Range and Target/Area).

FYI, the range can be calculated as `x.spell.system.range` and the target/area as something like this:

```
const strToShow = x.spell.system.area === null
  ? x.spell.system.target.value 
  : `${x.spell.system.area.value} ft ${x.spell.system.area.type}`
```

Here is a very rough mock example of what it could look like with a certain setting:

![image](https://user-images.githubusercontent.com/6516621/219652580-a57da017-cac4-432b-ad03-d8be798c4f5a.png)

**Comment by reonZ** [comment]
The problem is the space, i have very little space to work with, both the DC and components parts are small, and never change in size.

You are showing a stretched out version of the sheet and with the missing `cast` part to boot, i will not have the users extends their sheet every time.

Maybe i could remove both of them and have the range instead, but even then, i am not sure it would fit in.

**Comment by shemetz** [comment]
I agree, space is a problem, I thought just adding the ability to configure it would be enough, for users to decide individually what would work best for them, but it would probably be better to first find an actually good example of an alternative.

So here's what I suggest as a first step, to test what it looks like:  
1. remove the three rightmost columns (components, cast button, check/dc)
2. add a new column for Range
3. try a hover-only "Cast" in place 

for 2) The Range data should be pretty narrow;  I went through the list of spells now and the longest strings I saw were "1,000 feet" and "planetary". both of them short enough to take up half the remaining space at most.

I'd really like to get "Target"/"Area" there too, but the only way I managed to include it is with an ellipsis cutoff point after just a few words, which is usable but doesn't look great.  I also merged Target and Area, even though technically a spell might have both, I think.

for 3) - even though there may be room for it, I just think it's unnecessary to show the Cast button for every spell, I think revealing it on hover should be enough.  It might have to be hover-revealed in a way that replaces the content in another column (probably the rightmost column).  

When I get some more free time I'll try to see if I can make a better mock, or maybe even implement it locally.

**Comment by reonZ** [comment]
The layout have been revisited in the version `1.3.0`, the components and CHECK/DC sections have been removed and a range section replaces them, when hovering over the range, you will now get the spellcasting entry as well as the DC in the tooltip (it also uses a tooltip a bit nicer than the default browser one).

![Foundry_Virtual_Tabletop_NSHqm2Jvng](https://user-images.githubusercontent.com/651462/223200437-254fc104-1283-4041-a9cc-086b2c9e7c0a.jpg)

**Comment by shemetz** [comment]
Awesome!

I'd like to know, though - is there a reason the CAST button is at the 3rd column, rather than the rightmost (or even the leftmost)?  It doesn't bother me too much, but it seems natural to expect the most used buttons to be on one of the two sides.

**Comment by reonZ** [comment]
That is how it is on the regular tab, nothing special about it, and if you don't have the rights to edit the sheet, the cast button won't appear, leaving an empty space there instead of on the right side.
