### ISSUE TITLE
Focus Points don't show up on Cantrips (Psychic)

### ISSUE THREAD

**Issue by Monation** [reonZ/pf2e-spells-summary#9]
Psychics use Focus Points to Amp a few of their Cantrips (which are called Psi-Cantrips). This module doesn't show focus points on Cantrips when you hover over the "Focus" in Spell Category column.

![image](https://user-images.githubusercontent.com/9889274/223316024-dd691849-9eef-42fb-8b19-297b97c83571.png)

**Comment by reonZ** [comment]
The thing is, the system doesn't allow for cantrips to use focus points.

You are gonna have to help me understanding how you are having `amped` cantrips that are actually consuming focus points.

**Comment by reonZ** [comment]
I have tinkered something that should be helpful to you.

With version `1.4.0` if a focus cantrip name includes any of the words `amp`, `psi`, `psy`, `psychic` or `amped` between parentheses (i.e. `Shield (Amped)`), it will be considered as a psychic amped cantrip and will display the focus pool to be manipulated.
